name: Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build for ${{ matrix.environment }}
    strategy:
      matrix:
        environment: [chrome, firefox]
    steps:
      - uses: step-security/harden-runner@63c24ba6bd7ba022e95695ff85de572c04a18142 # v2.7.0
        with:
          egress-policy: audit
      - uses: actions/checkout@v4
      - run: corepack enable
      - uses: actions/setup-node@v4
        with:
          node-version-file: package.json
          cache: pnpm
          cache-dependency-path: pnpm-lock.yaml
      - run: pnpm install --frozen-lockfile
      - run: pnpm run zip --browser ${{ matrix.environment }}
      - uses: actions/upload-artifact@v4
        with:
          name: output-${{ github.run_id }}
          path: .output/*.zip
